name: Reports
run-name: reports

on:
  workflow_dispatch:
  push:

jobs:
  jacoco-reports:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Jacoco tests
        working-directory: ./smart-home/Platform
        run: ./gradlew jacocoTestReport

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: ./smart-home/Platform/build/reports/test/jacocoTestReport.csv

      - name: Push Badge
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Commit Coverage Badge'
          add: '*.svg'

      - name: Upload Coverage
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: jacoco report
          path: ./smart-home/Platform/build/reports/test
